import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import TanstackProvider from "@/providers/TanstackProvider";
import Footer from "@/components/layout/Footer";

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "Kicks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} antialiased`}>
        <TanstackProvider>
          <div className="py-6 md:py-8 bg-gray">
            <Navbar />
            {children}
            <Footer/>
          </div>
        </TanstackProvider>
      </body>
    </html>
  );
}
